_wandb:
    value:
        cli_version: 0.21.3
        e:
            ojlabb1ygze9x97lgiengf9c32wt1tm7:
                codePath: train_production_model.py
                codePathLocal: train_production_model.py
                email: jonathanschwartz30@gmail.com
                executable: /Users/jonathanschwartz/Documents/Social_Content/onefilellm_venv/bin/python
                git:
                    commit: 3a948515cd65eb29854355a37e6dc6126299cd4e
                    remote: https://github.com/filmboy3/training_model_PT.git
                host: MacBook-Pro.local
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/jonathanschwartz/Documents/Social_Content/QuantumLeap_Pose_Engine/train_production_model.py
                python: CPython 3.13.3
                root: /Users/jonathanschwartz/Documents/Social_Content/QuantumLeap_Pose_Engine
                startedAt: "2025-09-02T01:09:13.684566Z"
                writerId: ojlabb1ygze9x97lgiengf9c32wt1tm7
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.3
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
checkpoint:
    value:
        keep_best: true
        metric: val_total_loss
        save_dir: checkpoints/production
        save_frequency: 5
data:
    value:
        dataset_path: data/production_squats_10k.h5
        num_workers: 4
        pin_memory: true
        shuffle: true
        test_split: 0.1
        train_split: 0.8
        val_split: 0.1
loss_weights:
    value:
        exercise_weight: 0.5
        form_weight: 0.3
        pose_weight: 1
        uncertainty_weight: 0.1
model:
    value:
        dropout: 0.1
        hidden_dim: 256
        imu_dim: 6
        input_dim: 51
        max_seq_length: 200
        num_exercises: 10
        num_form_classes: 5
        num_heads: 8
        num_layers: 6
training:
    value:
        accumulation_steps: 1
        batch_size: 32
        gradient_clip: 1
        learning_rate: 0.0001
        num_epochs: 100
        patience: 15
        warmup_epochs: 10
        weight_decay: 1e-05
wandb:
    value:
        name: production-training-10k
        notes: Production training on 10K MuJoCo synthetic squat sequences
        project: quantumleap-pose-engine
        tags:
            - mujoco
            - synthetic
            - production
            - 10k-dataset
