_wandb:
    value:
        cli_version: 0.21.3
        e:
            11666j8qnwp9vcqvlx19d0vsbc2195qd:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "8589934592"
                codePath: smoke_test.py
                codePathLocal: smoke_test.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "475660075008"
                email: jonathanschwartz30@gmail.com
                executable: /Users/jonathanschwartz/Documents/Social_Content/onefilellm_venv/bin/python
                git:
                    commit: e12676c323bbdf8d10fdc3809ffd5e8ef51ecdb0
                    remote: https://github.com/filmboy3/training_model_PT.git
                host: MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/jonathanschwartz/Documents/Social_Content/QuantumLeap_Pose_Engine/smoke_test.py
                python: CPython 3.13.3
                root: /Users/jonathanschwartz/Documents/Social_Content/QuantumLeap_Pose_Engine
                startedAt: "2025-09-02T01:34:21.647792Z"
                writerId: 11666j8qnwp9vcqvlx19d0vsbc2195qd
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
            "4": 3.13.3
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
