_wandb:
    value:
        cli_version: 0.21.3
        e:
            1suej2he0ymot6pla0kwllsxplnlwr10:
                codePath: smoke_test.py
                codePathLocal: smoke_test.py
                email: jonathanschwartz30@gmail.com
                executable: /Users/jonathanschwartz/Documents/Social_Content/onefilellm_venv/bin/python
                git:
                    commit: e12676c323bbdf8d10fdc3809ffd5e8ef51ecdb0
                    remote: https://github.com/filmboy3/training_model_PT.git
                host: MacBook-Pro.local
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/jonathanschwartz/Documents/Social_Content/QuantumLeap_Pose_Engine/smoke_test.py
                python: CPython 3.13.3
                root: /Users/jonathanschwartz/Documents/Social_Content/QuantumLeap_Pose_Engine
                startedAt: "2025-09-02T01:31:42.424465Z"
                writerId: 1suej2he0ymot6pla0kwllsxplnlwr10
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
            "4": 3.13.3
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
